# Generated by Django 6.0.2 on 2026-02-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('discount', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=64)),
                ('info', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'db_table': 'banners',
            },
        ),
    ]
